version: "3.8"

services:
  logstash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logstash
    env_file:
      - .env
    environment:
      LS_JAVA_OPTS: ${LS_JAVA_OPTS:-"-Xms512m -Xmx512m"}
      # Pass-through of JDBC env vars used in pipeline
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JDBC_SCHEDULE: ${JDBC_SCHEDULE:-"*/30 * * * * *"}
      JDBC_PAGE_SIZE: ${JDBC_PAGE_SIZE:-1000}
      JDBC_LASTRUN_INITIAL: ${JDBC_LASTRUN_INITIAL:-"1970-01-01 00:00:00"}
    volumes:
      - ./pipelines:/usr/share/logstash/pipelines:ro
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - logstash-data:/usr/share/logstash/data
    restart: unless-stopped

volumes:
  logstash-data:
